- name: Check Ansible Ubuntu latest
  # You may pin to the exact commit or the version.
  # uses: roles-ansible/check-ansible-ubuntu-latest-action@5c775457431b589c763f6067bf688e9f45d4bd97
  uses: roles-ansible/check-ansible-ubuntu-latest-action@0.4.1
  with:
    # Paths to the ansible role or playbook you want to be tested.
For example './', 'roles/my_role/' or 'site.yml'

    targets: 
    # When testing playbooks you have to tell ansible
the group you that we write in our hosts file.
For example 'servers' or what group you are using
in the playbook you want to test!

    group: # optional
    # When testing playbooks you have to give us
one example host we should use to test your playbook.
For example 'server1.example.com'.
We only spawn one docker container that mean
we can only test one host at the time. Sorry

    hosts: # optional
    # When testing playbooks and you are using ansible galaxy,
you may be interested in installing your requirements
from ansible galaxy.
To do this please provide us either the role name directly
-> e.g. 'do1jlr.ansible_version'
or your requiements.yml file.
-> e.g. 'requirements.yml'

    requirements: # optional

    name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg


      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
